# Generated by Django 6.0.3 on 2026-05-06 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('flag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.flag')),
            ],
            options={
                'verbose_name_plural': 'Indizi',
            },
        ),
        migrations.CreateModel(
            name='Profilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profilo', models.ImageField(blank=True, null=True, upload_to='profili/')),
                ('punteggio', models.IntegerField(default=0)),
                ('livello', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('esperto', 'Esperto')], default='principiante', max_length=20)),
                ('flag', models.ManyToManyField(blank=True, to='main.flag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profili',
            },
        ),
        migrations.CreateModel(
            name='Sfida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('difficolta', models.CharField(choices=[('facile', 'Facile'), ('medio', 'Medio'), ('difficile', 'Difficile')], default='facile', max_length=20)),
                ('p_massimo', models.IntegerField()),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='sfide/')),
                ('link', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
            ],
            options={
                'verbose_name_plural': 'Sfide',
            },
        ),
        migrations.AddField(
            model_name='flag',
            name='sfida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sfida'),
        ),
        migrations.CreateModel(
            name='FileSfida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='sfide/files/')),
                ('sfida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sfida')),
            ],
        ),
        migrations.CreateModel(
            name='Partecipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(default='non_iniziata', max_length=20)),
                ('punteggio_ottenuto', models.IntegerField(default=0)),
                ('indizi_sbloccati', models.ManyToManyField(blank=True, to='main.indizio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sfida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sfida')),
            ],
            options={
                'verbose_name_plural': 'Partecipazioni',
                'unique_together': {('utente', 'sfida')},
            },
        ),
    ]
