# Generated by Django 6.0.3 on 2026-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfida',
            name='l_difficolta',
        ),
        migrations.AddField(
            model_name='sfida',
            name='difficolta',
            field=models.CharField(choices=[('facile', 'Facile'), ('medio', 'Medio'), ('difficile', 'Difficile')], default='facile', max_length=20),
        ),
    ]
