# Generated by Django 6.0.3 on 2026-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sfida_l_difficolta_sfida_difficolta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='livello',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('esperto', 'Esperto')], default='principiante', max_length=20),
        ),
    ]
