# Generated by Django 6.0.3 on 2026-03-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_utente_livello'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipa',
            name='indizi_sbloccati',
            field=models.ManyToManyField(blank=True, to='main.indizio'),
        ),
        migrations.CreateModel(
            name='FileSfida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='sfide/files/')),
                ('sfida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sfida')),
            ],
        ),
    ]
