# Generated by Django 6.0.3 on 2026-03-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partecipa_indizi_sbloccati_filesfida'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfida',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
